### ISSUE TITLE
Provide sample program for us to try

### ISSUE THREAD

**Issue by A11riseforme** [aliyunav/Finger#1]
Is is possible to provide the sample program for us to try on this tool? 

I noticed there were demonstration on three program in your blog: https://sec-lab.aliyun.com/2021/10/15/Finger%EF%BC%9A%E4%B8%80%E6%AC%BE%E5%87%BD%E6%95%B0%E7%AC%A6%E5%8F%B7%E8%AF%86%E5%88%AB%E7%A5%9E%E5%99%A8/, but I can't download it from virustotal as I have no enterprise account. 

I have tried to compile some file statically with symbol stripped, but finger just return recognize failed for all functions on IDA.

![image](https://user-images.githubusercontent.com/9150683/137596898-07331ce0-8a00-4116-a609-ab630fe336a9.png)

I am not sure if I have misconfigured the installation or it's the issue on your side =(

**Comment by aliyunav** [comment]
> Is is possible to provide the sample program for us to try on this tool?
> 
> I noticed there were demonstration on three program in your blog: https://sec-lab.aliyun.com/2021/10/15/Finger%EF%BC%9A%E4%B8%80%E6%AC%BE%E5%87%BD%E6%95%B0%E7%AC%A6%E5%8F%B7%E8%AF%86%E5%88%AB%E7%A5%9E%E5%99%A8/, but I can't download it from virustotal as I have no enterprise account.
> 
> I have tried to compile some file statically with symbol stripped, but finger just return recognize failed for all functions on IDA.
> 
> ![image](https://user-images.githubusercontent.com/9150683/137596898-07331ce0-8a00-4116-a609-ab630fe336a9.png)
> 
> I am not sure if I have misconfigured the installation or it's the issue on your side =(

This is the md5 list：["2622bd5396c70fd9702acf8720b395ad", "04b75469060b9a2aa986af3c1533c058", "eab14398a66bb088d0cfab4f7737c58d"], I am sorry that we can't directly provide sample program to you because of some requirements, please download them from virustotal.  
Your function recognition failed maybe due to the finger network connection problem yesterday, please try again.

**Comment by A11riseforme** [comment]
Okay I've tried again, seems the issue is fixed. the function recognition was successful. Thank you!
